### ISSUE TITLE
Set up backend authentication

### ISSUE THREAD

**Issue by jboolean** [opencollective/foundation-website#15]
Set up an auth provider for Netlify CMS.

Netlify Identity is not available on Vercel, so options are

1. Use GitHub OAuth with something like this https://www.component-driven.dev/articles/netlify-cms-github-oauth-vercel (easy)
2. Have custom deployment of [GoTrue](https://github.com/netlify/gotrue)/[Git Gateway ](https://github.com/netlify/git-gateway) for identity. (Harder)

In the past GitHub OAuth was hard to use and requires all editors to be repo contributors. But it doesn't require a backend with a db to manage a separate identity.

**Comment by jaison080** [comment]
Shall I do this
