### ISSUE TITLE
Support table editing in CMS

### ISSUE THREAD

**Issue by jboolean** [opencollective/foundation-website#17]
It was requested that the services table be editable in the CMS. Netlify CMS does not support editing tables (https://github.com/netlify/netlify-cms/issues/2845). 

Suggestion: create a custom widget that uses a more advanced markdown editor, like Toast UI. This may have to be implemented as a separate UMD library that can be loaded.

**Comment by SreejithNS** [comment]
I can contribute to it if you are working on it.

**Comment by jboolean** [comment]
I finally got it. 

Requires having a webpack build to build a custom version of Netlify CMS that loads an alternate markdown widget that I made (https://github.com/jboolean/netlify-cms-widget-markdown-toast-ui) and published to NPM .
