### ISSUE TITLE
collectives not showing up on the homepage

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#18]
The collectives are in the backend but don't show up on the front end.
<img width="1263" alt="Screen Shot 2022-06-06 at 5 18 44 AM" src="https://user-images.githubusercontent.com/88373348/172089084-83fd2173-789a-48ce-a0e0-e5519b177ec0.png">

**Comment by jboolean** [comment]
I see all these collectives in the first section of the page, where they are designed to show up. Perhaps it had not yet deployed when you checked? It can take a few minutes, or more if others at OC are running builds at the same time.

**Comment by carolineawoolard** [comment]
Yes, now it works!
