### ISSUE TITLE
people not showing up under Engineering and Design team

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#19]
The Engineering and Design Team is in the backend but doesn't show up in the front end -- is this because I added an additional "Department" called OC Network Affiliations? Additional Departments should not mess this up, but it is a change I made.
![Screen Shot 2022-06-06 at 5 22 46 AM](https://user-images.githubusercontent.com/88373348/172089211-e1b3165c-430b-4212-b582-8c6641d78c58.png)

**Comment by carolineawoolard** [comment]
Also, people are showing up under "Board" for some reason even though I keep changing it. Memo for example, should not be in the Board (Engineer and Design) and Sade should be under Community and Ops
![Screen Shot 2022-06-06 at 5 38 55 AM](https://user-images.githubusercontent.com/88373348/172090772-892c37db-936b-43e9-b773-7d15301df674.png)

**Comment by jboolean** [comment]
I see a department called "Platform Engineering and Design", and Memo is no longer under the Board. 
Perhaps your changes had not yet deployed when you checked? It can take a few minutes, or more if others at OC are running builds at the same time.

**Comment by carolineawoolard** [comment]
Yes, seems fixed now!
