### ISSUE TITLE
I can't click on EVENTS to rsvp for them

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#20]
I want to be able to click on a link for each event to be taken to that page to sign up - perhaps this was unclear in Memo's design, but this needs to be possible.

![Screen Shot 2022-06-06 at 5 24 23 AM](https://user-images.githubusercontent.com/88373348/172089359-a51bdc68-1146-456b-bb4c-53b0cd0c3130.png)

**Comment by jboolean** [comment]
Added this a while back. They are links now.
