### ISSUE TITLE
we need an editable text field below Events so that we can add links to PDFs + recordings (hosted elsewhere) for the Solidarity School we are running.

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#21]
See the Figma for how this field should look -- perhaps you are not there yet -- if so, sorry, excited to see it and play with editing it, when it's ready!

![Screen Shot 2022-06-06 at 5 28 47 AM](https://user-images.githubusercontent.com/88373348/172089744-e288ebc7-4563-4a54-83c9-e246730e8d58.png)

**Comment by jboolean** [comment]
Added a section in the CMS called "Editable blocks" and under it one called "Resources for events blurb" where this can be edited.
