### ISSUE TITLE
Copy edits and other small changes

### ISSUE THREAD

**Issue by natehn** [opencollective/foundation-website#24]
Love it! Here are some things I noticed.

### Text

- change "prepaid" in "Offer prepaid debit cards to your team" to "virtual" debit cards
- change "5%" in "5% if you raise over $500k" to  "6%"
- - "Learn more here." under fees can probably be removed
- For Sade, edit "Organier" to "Organizer"
- For Andrew, edit "member" to "Member"
- For Ember, change "staff" to "Staff"
- For Alina, change "Stuff" to "Staff"
- For Caroline, change to Germany and change flag
- For Nathan, change to New York
- For all locations, remove the whitespace between the city/state and the comma
- For Nia, Niki, Ebony, Robin: change to "Artist Organizer"
- For Ebony, change to United States and change flag
- For Guillermo, change to Mexico and change flag - or delete, since he is in there also as Memo
- Change category for "Social Impact Commons" to "Fiscal Sponsorship" and the same for NNFS
- Social Impact commons is based in USA

### Staff

- Sadé Swift is staff, not a board member

### Images/graphics

- some of the images have awkward cropping
- some of the images are a slightly different size, which affects the webpage spacing
- Bushwick Ayuda Mutua image not working

### Suggestions

- too many past events are included in the events area, and they are not visually delineated from upcoming ones (could they be "greyed out"?)

**Comment by jboolean** [comment]
Updated.
In the future, almost all these changes (including everything in the team section) can be made in the CMS at https://foundation-website-git-new-opencollective.vercel.app/admin . I'm wondering many things appear to have been entered with a space at the end of the text field? Maybe a cut and paste error from somewhere? I cleaned it up.

I made sure to lock the image aspect ratio so it should not longer change size. However, that does mean that images will be cropped if they are not of the aspect ratio  520 : 496. 

I'll leave the design suggestion to @Memo-Es.

**Comment by Memo-Es** [comment]
I added an extra state to differentiate past events from upcoming events
<img width="636" alt="Screen Shot on 2022-06-13 at 21-17-27" src="https://user-images.githubusercontent.com/49539954/173479575-af3c5573-10b0-40f4-a793-85d5a8bc0409.png">

cc @natehn
