### ISSUE TITLE
Make Collective name and picture clickable

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#25]
If someone sees a Collective in the rotating header they want to know more about, they should be able to click. It could open in a new window. I thought about maybe jumping to the all Collectives section of the page, but I actually think viewing a live Collective page is one of the best ways for someone to understand how this works, so opening a Collective directly seems like a good idea.

**Comment by jboolean** [comment]
Added the ability to provide a URL for featured collectives. Feel free to add any links in the CMS at https://foundation-website-git-new-opencollective.vercel.app/admin#/collections/configurableContent/entries/featuredCollectives
