### ISSUE TITLE
Screen real estate / formatting for Collectives section

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#26]
I don't think the section showing all the Collectives is playing nice with screen real estate.

1. items not responsive, get cut off. They should go down to a new row if they can't fit horizontally.

![Screen Shot 2022-06-08 at 10 17 42 AM](https://user-images.githubusercontent.com/5498878/172492742-0fba5b1e-9a06-44a9-ab52-4222b2f86422.png)

2. Clicking `view all` creates an insanely large section of the page, making it hard to navigate to other sections. I think it should either paginate within the section (with arrows like the features slideshow) or open in a new page just for all the Collective icons.

3. Long Collective names break the formatting of the rows, creating an odd extra space for Collectives without long names. The container should either be standard size for all items, or we should not enforce neat rows and have the items fit together and not line up all the time.

![Screen Shot 2022-06-08 at 10 21 45 AM](https://user-images.githubusercontent.com/5498878/172493093-3003721b-db45-42e5-aa4e-1f44d6abb6aa.png)

 4. After clicking `view all` there is no way to close the expanded section, and the link still says `view all` despite all being displayed. It should either say `close` or disappear (or not be needed due to changing how this section works per 2 above).

**Comment by jboolean** [comment]
@Memo-Es

**Comment by Memo-Es** [comment]
I fixed both events and Collectives titles to two lines and redirected the 'View all' buttons to: https://opencollective.com/foundation/events for events and https://opencollective.com/foundation#category-CONTRIBUTIONS for Collectives


<img width="1283" alt="WhatsApp Image 2022-06-09 at 4 35 04 PM" src="https://user-images.githubusercontent.com/49539954/173432925-f2837aba-aea6-4989-b320-d7770b6ca82b.png">

@jboolean @alanna

**Comment by jboolean** [comment]
@Memo-Es How's this? https://foundation-website-8n4d27olx-opencollective.vercel.app/

**Comment by Memo-Es** [comment]
That works @jboolean, take a look at https://github.com/opencollective/foundation-website/issues/57 as well
