### ISSUE TITLE
Make text in detailed lists smaller to improve readability

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#28]
I love the bold text for headlines, but there are a few places where the large text is preventing visually seeing the whole picture in one and losing the benefits of the visual format side of the communication.

![Screen Shot 2022-06-08 at 10 31 13 AM](https://user-images.githubusercontent.com/5498878/172494014-b312d424-3562-41a8-b244-bcdafa3db92d.png)

If the list text were smaller, and/or split into two columns (make the middle section wider) it would be easier to scan the full impact of the two headlines on either side, plus the detail in the middle, and how they relate.

![Screen Shot 2022-06-08 at 10 32 31 AM](https://user-images.githubusercontent.com/5498878/172494306-3f5a3f0f-bb58-4aa4-ab39-fdd145a2658e.png)

This section doesn't fit even on my very large screen expanded as much as possible, so it's hard to scan for the details I'm interested in, and impossible to see the overall picture. I lost context of what's at the top of each column so I can't understand the meaning of the symbols. The text is very large, but I think people are fine to read small text in a context like this. The spacing is also generous. I think we should make this smaller, tighter, or edit it down so the table fits within a standard laptop screen size (on mobile people get that only a small amount of info can be displayed at once).

![Screen Shot 2022-06-08 at 10 35 23 AM](https://user-images.githubusercontent.com/5498878/172494571-391ff536-1e10-459f-93ff-46b64a74be08.png)

This diagram is great, but it's too big and I can't take in the whole picture, which is critical for understanding its intended meaning. Make the $1000 one square, and the rest of the breakdown into a subdivided other square next to it, and make them smaller so you can see both side by side on one screen.

**Comment by jboolean** [comment]
@Memo-Es

**Comment by alanna** [comment]
Here I did a mockup of a clearer diagram

<img width="911" alt="Screen Shot 2022-06-13 at 8 53 51 AM" src="https://user-images.githubusercontent.com/5498878/173253228-9f29814d-bd69-40ca-8e92-8b5373c633aa.png">

**Comment by Memo-Es** [comment]
## Design update

### 1. 
 
I updated this section on desktop to have more room for the central content to fit in less vertical space

<img width="1192" alt="Screen Shot on 2022-06-13 at 22-12-33" src="https://user-images.githubusercontent.com/49539954/173485782-3883a621-5e22-440e-8197-4ef0b55f6c6a.png">

### 2. 

I compressed the comparison table in order for it to fit on a screen, adding the button to 'Show all features', and updating the text style of the left column to smaller text size.
 - If the table is expanded, the top row stays fixed on the top
<img width="1283" alt="Screen Shot on 2022-06-13 at 22-20-27" src="https://user-images.githubusercontent.com/49539954/173486651-b0e5bdbe-de3f-48e5-a88f-04d1f3c91529.png">

 - Related to this same section @jboolean, can you fix the grid lines to the edges of the window? So these spaces don't appear

![Annotation on 2022-06-13 at 22-27-05](https://user-images.githubusercontent.com/49539954/173487246-eaa32ebb-dc60-4158-9606-03aab41bd43b.png)

### 3. 

I updated the diagram so it can fit on a normal desktop screen along with the title and the fees below.

<img width="1283" alt="Screen Shot on 2022-06-13 at 22-28-08" src="https://user-images.githubusercontent.com/49539954/173487489-9414de7d-4582-4305-9f19-bd2cd8fc7005.png">

 - Same as the previous point, could you fix the diagram to the edges?

![Annotation on 2022-06-13 at 22-31-15](https://user-images.githubusercontent.com/49539954/173487708-d0b65b48-ff41-48aa-9ac4-28dcb31690dd.png)


@jboolean @alanna

**Comment by alanna** [comment]
Thanks @Memo-Es this looks much better! 

I'm going to raise a separate issue about the diagram because I think it could be improved a bit further but it's not really about readability size.

**Comment by jboolean** [comment]
@Memo-Es Check this out [foundation-website-iff8ud5ic-opencollective.vercel.app](https://foundation-website-iff8ud5ic-opencollective.vercel.app/)

After a couple hours I gave up on extending the table borders for now. I'm not sure how to create table borders that break out of the table without destroying the table layout

**Comment by Memo-Es** [comment]
The 'Show more features' button should stay at the end of the table, and change the direction of the chevron and change the tet to 'Show less features' @jboolean: 
<img width="1316" alt="Screen Shot on 2022-06-27 at 22-09-41" src="https://user-images.githubusercontent.com/49539954/176083935-0f847155-30bc-4114-84ea-8bdefdeb8a8f.png">

The top row should always be fixed, and opaque ([Here](https://d.pr/F0rO95) there is some see-through that looks weird) and with a divider line at the bottom 

Also, please remove the duplicated divider line at the bottom
![Annotation on 2022-06-27 at 22-13-57](https://user-images.githubusercontent.com/49539954/176084320-478622dc-a521-4ec8-93b1-cc4ec75d7bf8.png)

**Comment by Memo-Es** [comment]
For the table width, can't we have something like this for larger screens?

![Desktop](https://user-images.githubusercontent.com/49539954/176084600-c39fa76c-9550-4424-9fce-ff05fbdb7d5c.png)

[Reference here
](https://www.figma.com/file/asF21um9LrwMBGJHM6m2uz/OCF---Master-File?node-id=1933%3A16165)

**Comment by jboolean** [comment]
@Memo-Es Check this out https://foundation-website-git-28-opencollective.vercel.app/

For the last point, I think you mean to remove the width constraint (what I call the 'content container'). See what you think about that.

**Comment by Memo-Es** [comment]
Looks good @jboolean!

The only thing it seems missing is the divider line for the top line when scrolling
