### ISSUE TITLE
autofill isn't working on the CMS for the Country

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#30]
When I type in United States nothing comes up -- only what you see below
![Screen Shot 2022-06-12 at 7 49 45 AM](https://user-images.githubusercontent.com/88373348/173217638-5193c096-7095-40ad-b0ef-405f76c54b41.png)
![Screen Shot 2022-06-12 at 7 49 27 AM](https://user-images.githubusercontent.com/88373348/173217641-cc3394f8-c4f5-4c06-adb6-fde1dfb36e9a.png)

**Comment by jboolean** [comment]
:-D it's because I changed the label to "U.S.A." to match the design. 

Fixed it by adding a second label just for searching on separate from how it's displayed. Also changed the people set to UM to US.
