### ISSUE TITLE
"Pricing" anchor should start at the text above the diagram

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#31]
The pricing anchor should jump to the text above the diagram (right now it jumps to the diagram below the text)

"We ask for 5% of the money raised to pay our team and build technology you ask for."

![Screen Shot 2022-06-12 at 7 56 06 AM](https://user-images.githubusercontent.com/88373348/173218216-94d932a8-6d47-401b-8cb1-4d2aa1b66d33.png)

**Comment by jboolean** [comment]
Whoops, I had it in the _services_ section.
