### ISSUE TITLE
Edit the fees text 

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#33]
**This text:** 
* We take 5% for crowdfunding done on the site. Third-party payment processors (like Stripe and Paypal) charge separate fees on each transaction made using their service. Learn more here. We take 4-8% for bank transfers and checks: 8% for up to 500k raised; 6% for up to 1 million raised; 4% for over a million raised.

**Should become:**
* We say 8% because Open Collective Foundation takes 5% for crowdfunding done on the site and third-party payment processors (like Stripe and Paypal) charge separate fees **that average 3%** on each transaction made using their service. Learn more [here](https://docs.opencollective.foundation/how-it-works/fees). We take 4-8% for bank transfers and checks: 8% for up to 500k raised; 6% for up to 1 million raised; 4% for over a million raised.

![Screen Shot 2022-06-12 at 8 09 34 AM](https://user-images.githubusercontent.com/88373348/173219612-331e5a92-8bee-45c6-a25b-ab1ca80db0eb.png)

**Comment by jboolean** [comment]
Updated, and also made this editable under "Editable blocks > Fees blurb"
