### ISSUE TITLE
links are not underlined in the editable field

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#36]
I didn't know that I could click on these links because they are not blue or underlined -- please make it obvious that this is a link.

<img width="1365" alt="Screen Shot 2022-06-12 at 9 05 28 PM" src="https://user-images.githubusercontent.com/88373348/173249240-f24a475b-c040-497b-b3fa-0ce4fd1f1028.png">

**Comment by jboolean** [comment]
I also noticed this and changed it.
