### ISSUE TITLE
Header size jumping around

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#37]
![99668e41e1610fd0aee9af45c2e3ef9d](https://user-images.githubusercontent.com/5498878/173253030-4f493609-98dc-417f-be49-2214f0ea2e9e.gif)

Make all the header images the same size. There's also a few oddly cut off in the crop.

**Comment by jboolean** [comment]
I think the jumping issue here is actually the text.

**Comment by natehn** [comment]
Yes, definitely appears to be the text changing in length due to different Collective names. Maybe just adding some flexible space below could do the trick?

**Comment by Memo-Es** [comment]
+1 @jboolean let's fix the height so it doesn't jump
