### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by jboolean** [opencollective/foundation-website#38]
Do you have a new favicon to use? The one on the old site is low res.

**Comment by carolineawoolard** [comment]
Here you go 
![OCF-Logo (2)](https://user-images.githubusercontent.com/88373348/173279029-078b767d-b46a-4467-9e8d-a8e323718dae.svg)
![OCFlogo-large (1)](https://user-images.githubusercontent.com/88373348/173279031-c7f3c9fe-8519-4826-9a4c-12054e9db884.png)
