### ISSUE TITLE
Make a mode for posting content where I can "hide" Collectives 

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#39]
I want to be able to "turn off" or "hide" Collectives while I wait for their full approval to use their imagery and feature them.

![Screen Shot 2022-06-13 at 4 06 32 PM](https://user-images.githubusercontent.com/88373348/173371972-5871d64f-62af-46bd-8eb7-0848765918de.png)

**Comment by jboolean** [comment]
Added a "visible" option to collectives
