### ISSUE TITLE
Join team link

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#40]
This doesn't link to anything

<img width="276" alt="Screen Shot 2022-06-14 at 9 45 10 AM" src="https://user-images.githubusercontent.com/5498878/173450746-51d242d7-b3e2-4f6f-b062-f48f1e771c20.png">

For now direct it to https://opencollective.com/hiring

Can the icon say `global` instead?

**Comment by alanna** [comment]
OK let's take this out completely then, and find another way to handle recruitment when needed.

**Comment by Memo-Es** [comment]
It seems that we can close this issue now
