### ISSUE TITLE
responsiveness issue on large mobile

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#43]
<img width="390" alt="Screen Shot 2022-06-14 at 8 29 51 PM" src="https://user-images.githubusercontent.com/5498878/173531595-ed8ac899-4b8f-4dcc-ba0c-c962a65c7ef0.png">

Reported by BenP

**Comment by jboolean** [comment]
I see you're at 450 and our breakpoint is at 428. Do you propose changing the breakpoint @Memo-Es ?

**Comment by Memo-Es** [comment]
@jboolean Yes! Let's bring it up to 468 to break for mobile. This also happens between desktop and tablet: 
<img width="1011" alt="Screen Shot on 2022-06-27 at 21-45-42" src="https://user-images.githubusercontent.com/49539954/176081041-fd61a1c3-ff3c-4e36-a9ea-e5cc0fee426f.png">
 It should break to the next point before these weird things happen

**Comment by jboolean** [comment]
Updated mobile breakpoint
