### ISSUE TITLE
Improve fees diagram

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#44]
The diagram started like this:
![172494571-391ff536-1e10-459f-93ff-46b64a74be08](https://user-images.githubusercontent.com/5498878/173547946-766af4d3-16a0-4d27-8b8a-705ca2b62103.png)

I suggested this:
<img width="911" alt="173253228-9f29814d-bd69-40ca-8e92-8b5373c633aa" src="https://user-images.githubusercontent.com/5498878/173547974-21634644-2eb4-4c63-a6ef-8d03f3d54315.png">

Now we have this:
<img width="1283" alt="173487489-9414de7d-4582-4305-9f19-bd2cd8fc7005" src="https://user-images.githubusercontent.com/5498878/173548003-afa65496-44c2-4461-bc8d-4ba8283f1783.png">

The issue I still have is the amount taken out for fees takes up much more visible space than the actual proportion, which makes it look like we take way more fees than we actually do.

If it were mathematically accurate in this design it would look like this:
<img width="1119" alt="Screen Shot 2022-06-14 at 9 57 28 PM" src="https://user-images.githubusercontent.com/5498878/173550423-44d22701-db45-4904-b99f-8a299f1aa29a.png">

But this isn't great because the text labels would be tiny on the fees section.

So, my suggestion is, either put the labels outside the actual boxes with arrows, or a zoom-out design, like this:
<img width="1112" alt="Screen Shot 2022-06-14 at 10 02 46 PM" src="https://user-images.githubusercontent.com/5498878/173553092-dcd6b968-d1e9-44fe-abe2-c82c85bf8bb2.png">

Or a different kind of diagram, like this:
![chart-svg](https://user-images.githubusercontent.com/5498878/173554623-8a29c8ac-e9a8-460f-815f-3191ff728566.png)

I don't mean to nitpick, but one of the key hurdles we have to get over in marketing is making people feel OK about the fees, so we don't want to make them look bigger than they are.

**Comment by Memo-Es** [comment]
I tuned the text down as well so it also aids to the perception of fees being small:
<img width="1065" alt="Screen Shot on 2022-06-27 at 21-36-29" src="https://user-images.githubusercontent.com/49539954/176079922-541ec88f-f618-4b22-b55f-7a186a1b35f9.png">
For the record, I initially tried to be mathematically accurate, but it looks super weird, I agree with the intent of making fees smaller, and I think making it small in size and having it with a considerably smaller text achieves this without breaking the design.

**Comment by Memo-Es** [comment]
I don't see an issue to be solved here

**Comment by Memo-Es** [comment]
[The latest design](https://www.figma.com/file/asF21um9LrwMBGJHM6m2uz/OCF---Master-File?node-id=1203%3A12792&t=xRanVcQF8pOdFnbH-3) fix hasn't been implemented yet @jboolean

**Comment by jboolean** [comment]
It was implemented on the linked PR (https://github.com/opencollective/foundation-website/pull/100). My intent was to let you review it before merging it in, but I'll just go ahead and merge it now.
