### ISSUE TITLE
No image on social share

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#45]
![Screen Shot 2022-06-15 at 12 21 29 PM](https://user-images.githubusercontent.com/5498878/173710765-68fb9e66-7254-402e-b363-81ffbbac70ac.png)

No image pulling through on Twitter or Slack either.

![Screen Shot 2022-06-15 at 12 23 39 PM](https://user-images.githubusercontent.com/5498878/173710934-e1b68588-894b-4425-8c5a-0d50d01e9025.png)

**Comment by jboolean** [comment]
@Memo-Es do you have a social image and other meta info?

**Comment by Memo-Es** [comment]
**Metadata:**
Meta description: OC Foundation offers nonprofit status + fundraising + money management software to aligned groups.
Social image is at the bottom here: https://www.figma.com/file/asF21um9LrwMBGJHM6m2uz/OCF---Master-File?node-id=30%3A10849
<img width="681" alt="Screen Shot on 2022-06-27 at 21-30-24" src="https://user-images.githubusercontent.com/49539954/176078841-23eacecc-9f7b-424d-b882-0a7747a74487.png">
@jboolean

**Comment by jboolean** [comment]
Added meta tags
