### ISSUE TITLE
Header: Rotating Collectives don't link out

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#46]
The rotation of collective name & image should link out to the respective collective's OC page. I got it working once, but it doesn't currently work.

![image](https://user-images.githubusercontent.com/64920686/175178570-5a66a438-ce17-46c8-a3c1-b279eadb21b1.png)

**Comment by kaylarep** [comment]
@jboolean I'm unable to access thru this link, can you possibly help me out?

![image](https://user-images.githubusercontent.com/64920686/175656872-b4a0a04c-88ea-46f8-9e9d-6ff5323348b3.png)

would like to leave this open till I get the links in.

**Comment by Memo-Es** [comment]
We might need help from @carolineawoolard

**Comment by jboolean** [comment]
@kaylarep added you
