### ISSUE TITLE
Extend rotating Header duration

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#48]
I would ask to add 3 seconds to each slide in the header.  It currently rotates too quickly imo.

(A good rule of thumb is to read the whole text out loud + look at the image and then add 3 seconds.)

https://www.loom.com/share/0ae04d623c6847cea5a72f48acb5a10f

**Comment by kaylarep** [comment]
![image](https://user-images.githubusercontent.com/64920686/175365013-e16f1129-11c6-4027-bae7-c9176bc2781a.png)

[additional user feedback from our [Update](https://opencollective.com/foundation/updates/ocf-has-a-fab-new-website)]

**Comment by jboolean** [comment]
@kalarep here's what it looks like at 6 seconds: https://foundation-website-git-48-opencollective.vercel.app/ 
Good?

**Comment by kaylarep** [comment]
@jboolean thank you! can you up to 8 seconds please?

**Comment by jboolean** [comment]
Upped to 8 seconds at this preview link

**Comment by kaylarep** [comment]
thank you!
