### ISSUE TITLE
The Process: Link out from graphic

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#49]
In this graphic, can each step link out?
![image](https://user-images.githubusercontent.com/64920686/175179822-774e197b-4644-47a5-a6ac-20714ac58c97.png)

**Apply**: https://opencollective.com/foundation/apply
**Meet Us**: Can jump to Community Events section of this homepage (are there capabilities to have anchored links on this homepage?) 
**Set Up Your Page**:  I would probably want to link this out to the Docs, but I think we are trying not to do this? Any suggestions of where else this could link? or perhaps there's a need for a 'How to Apply' page/section on this homepage
**Raise funds**: again, I would likely link out to the docs. Or this could link to a blog post about fundraising//could use a 'Conversation' for this

**Comment by jboolean** [comment]
@Memo-Es what do you think of an image map?

**Comment by Memo-Es** [comment]
What's easier for you @jboolean? An image map like this or an SVG-based solution?
Ideally, we should provide feedback with a hover state if we make those clickable, but if that sounds like a more sophisticated solution and the image map is more accessible, we can start with that.

**Comment by kaylarep** [comment]
might need @carolineawoolard scoping input about where they should link to.

**Comment by carolineawoolard** [comment]
The whole thing can link to https://opencollective.com/foundation/apply if needed -- I will do this because Kayla feels strongly about it, but imho the CTA "apply" is already everywhere.

**Comment by jboolean** [comment]
Preview https://foundation-website-git-link-process-graphic-opencollective.vercel.app/

**Comment by Memo-Es** [comment]
I think it needs a hover (Active on touch screens) state to make it clear 
Resting | Hover
--------|-------
<img width="1020" alt="Screen Shot on 2022-12-03 at 15-52-12" src="https://user-images.githubusercontent.com/49539954/205463621-f550093d-afa4-4d6a-8584-1691af8df568.png"> | <img width="1019" alt="Screen Shot on 2022-12-03 at 15-51-40" src="https://user-images.githubusercontent.com/49539954/205463622-27360045-ffda-478b-b380-e15133efa66f.png">

@jboolean
