### ISSUE TITLE
No link in 'privacy policy' for newsletter

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#50]
Not sure which privacy policy this should link out to, but think it should link to something

![image](https://user-images.githubusercontent.com/64920686/175183922-1639d6c3-dd18-4d1e-84a5-f5c9f7333b2a.png)

**Comment by kaylarep** [comment]
@alanna  do you know where this should link to?

**Comment by alanna** [comment]
There is no need to have this tickbox at all, just take it out. This just signs them up for the OC mailing list.

**Comment by Memo-Es** [comment]
@alanna, isn't this a GDPR issue?

**Comment by alanna** [comment]
We can change it to say "the open collective newsletter" if needed

**Comment by jboolean** [comment]
Removed the checkbox
