### ISSUE TITLE
Add link to network row

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#51]
I'd love to link to something in either the OC website or blog from this blurb to provide additional context for this information.

![image](https://user-images.githubusercontent.com/64920686/175366042-48461af9-9b54-4024-bb86-db27a56a7890.png)

**Comment by jboolean** [comment]
@Memo-Es ?

**Comment by Memo-Es** [comment]
I'm not sure where this should link to. @carolineawoolard, any ideas?

**Comment by carolineawoolard** [comment]
@jboolean in the future this can link to http://opencollective.com/about but that does not exist yet, so for now you can link to http://opencollective.com/e2c

**Comment by jboolean** [comment]
How's this? https://foundation-website-mhogwee2w-opencollective.vercel.app/

It's not obvious it's a link.
