### ISSUE TITLE
Add links for context to carousel

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#54]
Also add links to each of these. Without it, this is a lot of jargon, a lot of terms that new people may not be familiar with at all. 

![image](https://user-images.githubusercontent.com/64920686/175369294-69777003-1420-4a56-a973-8397f2fa493d.png)

**Comment by jboolean** [comment]
What are the urls you'd like? I am concerned about asking using to click moving text.

@Memo-Es

**Comment by kaylarep** [comment]
i think its ok since it freezes once you hover. will ask the team for their thoughts

**Comment by Memo-Es** [comment]
@jboolean, I think it's ok; as @kaylarep mentions, it stops when you hover over it. Can you confirm this can be edited using the CMS?

**Comment by jboolean** [comment]
Here, I've added the ability to edit it under Editable blocks > service ticker

**Comment by kaylarep** [comment]
can i leave this open and assigned to me? (so i remember to get to it once i have better clarity about what is/isn't ok to link out to).

**Comment by carolineawoolard** [comment]
@kaylarep did you do this? trying to close out issues so Julian is clear about what to work on.
