### ISSUE TITLE
Freeze First Row of "Is OC Foundation Right for You?"

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#55]
![image](https://user-images.githubusercontent.com/64920686/175370877-7db75c81-1a29-4856-bda5-cf0df569c4c9.png)

If we are unable to make edits to this chart, it's really important to freeze the top row of this chart for the duration of the time the user is on the chart. 

Otherwise it looks like this halfway through: 
![image](https://user-images.githubusercontent.com/64920686/175370633-d7d0d731-402e-4853-8aaf-5747d3f402e0.png)

and it becomes pretty unhelpful and takes up a lot of space, expecting users to scroll up and down again and again isn't intuitive.

For me, I'd rather not have it on the page at all if we cannot do anything about this . It could go on its own page perhaps.

(also, the zoom again is a problem for me. It's very large. Starts looking better around 80%)

**Comment by kaylarep** [comment]
- [ ] + link to 'Fees' page here 
![image](https://user-images.githubusercontent.com/64920686/175374028-57f08faa-0e1e-4dcb-bc76-7682b0ea7052.png)

**Comment by jboolean** [comment]
Closing as a duplicate to #17 and #28.

**Comment by kaylarep** [comment]
> The concern about the table length may already be addressed here #28, which you can preview here [ttps://foundation-website-git-28-opencollective.vercel.app](https://foundation-website-git-28-opencollective.vercel.app/)

that looks much better, thank you @jboolean !

---

> * [ ]  + link to 'Fees' page here
>   ![image](https://user-images.githubusercontent.com/64920686/175374028-57f08faa-0e1e-4dcb-bc76-7682b0ea7052.png)

is this ^ doable? (or i can just do it myself once I have access?)
