### ISSUE TITLE
Community Events feedback (lower priority)

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#57]
- It would nice to have a Calendar view of these events
- Can we grey out the past events? (or not display them at all?)  It's confusing to see all these events when a majority aren't active
- would be interesting to figure out how to integrate our wider community (our hosted group's) events into this. 
   - possible as a 'Submit an event' form. I think it could be fairly easy to have OCF team moderate & publish
   - would probably want this as a separate page/section

**Comment by jboolean** [comment]
@Memo-Es

**Comment by Memo-Es** [comment]
I agree with this feedback, and it's also a simple change.

@jboolean I included two divisions in the events section: Upcoming and past events:

<img width="1291" alt="Screen Shot on 2022-06-27 at 21-02-59" src="https://user-images.githubusercontent.com/49539954/176074460-60626dfb-d236-4ff9-a668-07dd5dc7c5cc.png">

Note: Remember that the 'View more' button should take you to: https://opencollective.com/foundation/events

**Comment by jboolean** [comment]
Separated event sections
Preview: https://foundation-website-git-57-opencollective.vercel.app

Link change is on #26

**Comment by Memo-Es** [comment]
One last thing on this one @jboolean I think having 1 line for upcoming events and another one for past events is enough so we don't use a lot of vertical space, like the reference [here](https://github.com/opencollective/foundation-website/issues/57#issuecomment-1168126915)
