### ISSUE TITLE
Need links in 'Resources for Events' section

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#58]
![image](https://user-images.githubusercontent.com/64920686/175378676-885cc60b-51e0-4225-8c12-75dbe1dcbc43.png)

This is a lot of jargon without context.

If we don't have good context yet for these, could even just publish an Update that describes what each is, and link to that

- [ ] Can we also invite people to join #ocf slack channel in this blurb? (we don't have that anywhere on the homepage yet)

**Comment by jboolean** [comment]
This is editable here https://opencollective.foundation/admin#/collections/editableBlocks/entries/resourcesForEvents

I'm not sure who this issue is directed to. Please tag whoever is responsible for this copy!

**Comment by kaylarep** [comment]
@carolineawoolard ?

**Comment by alanna** [comment]
I edited this section to make it simpler
