### ISSUE TITLE
Link to Eligibility Requirements somewhere prominent

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#60]
This is key information to applying groups. It's in the Docs, think it deserves highlighting as a step in the process. If I was an applying group, this would be the first information I would look for. It should not take any digging to find it.

If we don't want to link to the Docs, we could consider adding an 'Eligibility' section to this homepage

**Comment by jboolean** [comment]
@Memo-Es 

Please tag anyone who could help scope out this issue more.

**Comment by Memo-Es** [comment]
I agree with @natehn. I have the feeling we could take things OUT of this page instead of including more stuff

**Comment by kaylarep** [comment]
I'd be fine taking things out if it means we add in the Eligibility requirements. 

If I am applying to something, one of the first things I will look for is Eligibility requirements. If they aren't easily findable, I find this very questionable. When I am pushed to 'Apply' repeatedly and don't know if iI am even eligible, that's also questionable.

I want to know if I am eligible before I spend time diving into something. I wouldn't look into 'Community' or 'Events' if I am not even in the community yet.

at minimum, can we link to 'Eligibility' somewhere before an Apply button? 

Groups can go thru our entire application flow without once seeing if they are even eligible.  Or perhaps we want to edit our 'About' section to directly include these requirements.

**Comment by kaylarep** [comment]
also, our eligibility requirements really arent that long https://docs.opencollective.foundation/getting-started/eligibility

**Comment by natehn** [comment]
I must say, I continue to disagree. I'll add it to the OCF team meeting agenda for this week.
