### ISSUE TITLE
Add 'About' either to header or footer or both

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#61]
An 'About' page/section is often the first thing I look for on a website. In this page I expect to learn:
- About the company (address, phone, email)
    - founding information
    - values/mission (if this isn't provided in a clear and direct way & with sufficient context, its a big red flag for me)
    - how it works (the platform, fiscal hosting, fiscal hosting on the platform)
        - as a donor
        - as a collective admin
        - as an expense payee?
- About the team
- maybe a hiring page/section if this isn't a separate 'Careers' / 'Hiring' link in the footer
- maybe all the information in the https://docs.opencollective.foundation/about/official-information-and-documents page too - or at least a link to it
- maybe eligibility requirements
- probably a link to the docs where most of this info lives anyways
- information about Open Collective. OCF is part of a bigger ecosystem, this is a good place to direct there imo

**Comment by jboolean** [comment]
Please tag anyone who could help scope out this issue more

**Comment by kaylarep** [comment]
hmm I'm a bit frustrated to have this issue closed, as I feel this is important feedback. 

i didn't really get a chance to give this sort of feedback till now, so I'm not sure when would have been/ or would be a better time. is there plans to have a meeting with the whole team specifically about this? or did i just miss the boat and its done?
