### ISSUE TITLE
Add "Blog" to Nav - and Edits to the 'Blog' Section

### ISSUE THREAD

**Issue by kaylarep** [opencollective/foundation-website#77]
![image](https://user-images.githubusercontent.com/64920686/187531771-700d7010-cc4b-448f-b58a-18b291b9179b.png)

- [ ] It doesn't appear to be auto-updating. (Is it meant to?) We have more recent OCF posts than this that are not appearing here.
- [ ] can 'our blog' and `view more` link out to 'https://blog.opencollective.com/tag/ocf' ?
- [ ] The RSS link is broken for me

**Comment by alanna** [comment]
I would also like:

* A link to blog in the top nav bar
* Fewer posts shown in the blog section but more data per post, pulling through the image and the first sentence after the title at least.

**Comment by alanna** [comment]
Also, do we like how the blog section is all the way at the bottom? I think it makes more sense to go under the events section.

**Comment by carolineawoolard** [comment]
Agree @jboolean the blog should be in the nav bar, should appear after Events, should auto update, and should link to https://blog.opencollective.com/tag/ocf/

(ignore the request for fewer posts shown and more data per post as we will be blocked waiting for Memo)

**Comment by jboolean** [comment]
I'm not sure what you're seeing about updates not coming through. It's updated twice daily.

**Comment by carolineawoolard** [comment]
I agree - I can close this issue once you add Blog to the Nav and move it up.

**Comment by jboolean** [comment]
please take a look at this preview https://foundation-website-l3g9vwosy-opencollective.vercel.app/

**Comment by carolineawoolard** [comment]
perfect - merge and close!
