### ISSUE TITLE
Improvements to the Events section

### ISSUE THREAD

**Issue by alanna** [opencollective/foundation-website#78]
![Screen Shot 2022-09-02 at 10 16 44 AM](https://user-images.githubusercontent.com/5498878/188022428-b86502e4-57c1-42fe-aa41-710a0bce6fe3.png)

* Reverse the order so next event coming up is on top instead of furthest out
* Reduce to two rows of events to save some screen space
* Past events not working - I think this can be removed as we want to focus on future events people can sign up to

**Comment by carolineawoolard** [comment]
@jboolean agree - you need to reverse the order so the next event is at the top. Please DO keep past events and fix it. No need to make 2 rows as we will be waiting on Memo for too long.
