### ISSUE TITLE
compensation html being modified before serve

### ISSUE THREAD

**Issue by mixmix** [opencollective/foundation-website#85]
When we visit https://opencollective.foundation/compensation/
the html and js load, but the page has none of the targets for vue left to mutate

e.g. this line https://github.com/opencollective/foundation-website/blob/master/src/compensation/index.html#L182
```html
          <span class="text-body1"> (hourly: ${{ hourlyPay }}) </span>
```
is served up as :
```html
          <span class="text-body1"> (hourly: $) </span>
```

i.e. something is processing this code before serving, which breaks the page

**Comment by mixmix** [comment]
Possible solutions:
1. teach eleventy to leave that file alone
2. extract all the template stuff into JS, so that it can't be touched by eleventy

**Comment by jboolean** [comment]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/406931/202232721-2369774b-864f-4b6b-8ae9-ddeaad309341.png">
Try changing the htmlTemplateEngine to false.

**Comment by mixmix** [comment]
Choice! that worked thanks @jboolean 
I didn't have time to dig into the docs yesterday, wanted to write this down.

Working now @alanna
