### ISSUE TITLE
add “Values” to the Nav, after Team, before Docs

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#88]
"Values" will be a text-based section where we talk about Solidarity as Guiding principle and should be an editable text box similar to the "resources for events" styling, but allowing it to be a bit longer. It will also link to the compensation calculator.

![Screen Shot 2022-11-17 at 9 39 56 AM](https://user-images.githubusercontent.com/88373348/202397776-c8086a6b-3306-4dc2-a0e2-93f05812a810.png)

**Comment by jboolean** [comment]
@carolineawoolard Is it okay if I publish this as empty at first or do you have some initial copy?

**Comment by carolineawoolard** [comment]
Yes it can be empty now as I will fill it with copy from this https://docs.google.com/document/d/1AR1FmXDq5-SVxCXqbJOJoOYgZ_TadnHGIX4FcvUKnlE/edit?usp=sharing
