### ISSUE TITLE
need to be able to share specific links to Docs

### ISSUE THREAD

**Issue by carolineawoolard** [opencollective/foundation-website#90]
As staff of OCF, I want to be able to share a link to a specific page within the docs with a collective. 

Is there a way to be able to share an anchor / link to Docs from within the OCF website? 
For example, How to Apply (seen below) should have a link like https://docs.opencollective.foundation/getting-started/how-to-apply **If so, please implement special links like above!**

**If not,** we need to move docs to its own page, perhaps opencollective.foundation/docs so that each link works again, or remove docs from the homepage again and simply have "Docs" in the Nav take you to https://docs.opencollective.foundation/ as we had before, going back to the land where people are lost in Docs with no way to get back to the opencollective.foundation homepage ;)

![Screen Shot 2022-11-17 at 10 01 44 AM](https://user-images.githubusercontent.com/88373348/202402405-f54b281e-8bfb-4d5a-bfce-fdf30e3ffb79.png)

**Comment by jboolean** [comment]
@carolineawoolard 

I implemented a possible solution here: https://github.com/opencollective/foundation-website/pull/94

It allows a url parameter `?docs=`. So for instance a URL could look like https://opencollective.foundation?docs=getting-started/how-to-apply

Preview: https://foundation-website-git-docs-link-opencollective.vercel.app/?docs=getting-started/how-to-apply

If that works, I'll merge it in.

**Comment by carolineawoolard** [comment]
Yes, please merge it - thank you @jboolean

**Comment by carolineawoolard** [comment]
Then close this issue.
